services:
  frontend:
    build:
      context: contextPath
      dockerfile: Dockerfile
    ports:
      - "5480:5480"
    networks:
      - frontend-net
    volumes:
     - .:/app
     - /app/node_modules
    environment:
    - PORT=5480                 # App server port
    - DEV_API_SERVER_PORT=5481  # Development API server port
    - VITE_DOCKER_MODE=true
    tty: true
    stdin_open: true
    command: tail -f /dev/null
 
  backend:
    build:
      context: contextPath
      dockerfile: Dockerfile
    ports:
      - "5481:5481"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - frontend-net
      - backend-net
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/post-db
  
  db:
    build:
      context: contextPath
      dockerfile: Dockerfile
    networks:
      - backend-net
      - db-net
    env_file:
      - .env 
    volumes:
      - post-vol:/var/lib/posgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    build:
      context: contextPath
      dockerfile: Dockerfile
    volumes:
      - redis-vol:/data
    networks:
      - db-net
      - backend-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: until-fail

volumes:
  redis-vol:
  post-vol:

networks:
  frontend-net:
  backend-net:
  db-net: