services:
  frontend:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: ISW
    ports:
      - "5480:5480"
    networks:
      - frontend-net
    environment:
    - PORT=5480                 # App server port
    - DEV_API_SERVER_PORT=5481  # Development API server port
    - VITE_DOCKER_MODE=true
    - KOTTSTER_API_URL=http://localhost:5480 
    tty: true
    stdin_open: true
    command: sh /app/scripts/dev.sh
 
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5481:5481"
    volumes:
      - .:/src:ro 
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - frontend-net
      - backend-net
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/db
  
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    networks:
      - backend-net
      - db-net
    env_file:
      - .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8.6.0-alpine
    volumes:
      - redis-vol:/data
    networks:
      - db-net
      - backend-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  redis-vol:
  post-vol:

networks:
  frontend-net:
  backend-net:
  db-net: